blueprint:
  name: Bluetooth MAC → Person Location Attribution
  description: >
    Assigns device_tracker locations based on Bluetooth MAC connections to
    person source devices. Person priority is determined by input order.
    Each MAC maps to its own target device_tracker.
  domain: automation

  input:
    persons:
      name: Persons (priority order)
      description: First person has highest priority
      selector:
        entity:
          domain: person
          multiple: true

    bluetooth_macs:
      name: Bluetooth MAC Addresses
      description: Ordered list of MACs (AA:BB:CC:DD:EE:FF)
      selector:
        object:

    target_device_trackers:
      name: Target Device Trackers
      description: Ordered list — must match MAC order
      selector:
        object:

    bluetooth_sensors:
      name: Bluetooth Connection Sensors (Optional)
      description: >
        Optional: Bluetooth connection sensors to monitor for faster updates.
        Leave empty to only trigger on person state changes.
      default: []
      selector:
        entity:
          domain: sensor
          multiple: true

    default_gps_accuracy:
      name: Default GPS Accuracy
      description: Default GPS accuracy in meters when not available from person entity
      default: 50
      selector:
        number:
          min: 1
          max: 500
          unit_of_measurement: meters

mode: restart

trigger:
  - platform: state
    entity_id: !input persons
    id: person_state_changed
  - platform: state
    entity_id: !input bluetooth_sensors
    attribute: connected_paired_devices
    id: bluetooth_changed

variables:
  people: !input persons
  macs: !input bluetooth_macs
  targets: !input target_device_trackers
  default_accuracy: !input default_gps_accuracy

  match: >
    {%- set result = '' -%}
    {%- for i in range(macs | length) -%}
      {%- if result == '' -%}
        {%- set mac = macs[i] | lower -%}
        {%- for person in people -%}
          {%- if result == '' -%}
            {%- set source = state_attr(person, 'source') -%}
            {%- if source -%}
              {%- set sensors =
                device_entities(device_id(source))
                | select('match', '.*bluetooth_connection$')
                | list -%}
              {%- if sensors | length > 0 -%}
                {%- set devices =
                  state_attr(sensors | first, 'connected_paired_devices') or [] -%}
                {%- set devices_lower = devices | map('lower') | list -%}
                {%- if mac in devices_lower -%}
                  {%- set result = person ~ '|' ~ mac ~ '|' ~ targets[i] -%}
                  {{ result }}
                {%- endif -%}
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}
        {%- endfor -%}
      {%- endif -%}
    {%- endfor -%}

condition:
  - condition: template
    value_template: "{{ match | length > 0 }}"

action:
  - variables:
      person: "{{ match.split('|')[0] }}"
      mac: "{{ match.split('|')[1] }}"
      target: "{{ match.split('|')[2] }}"
      lat: "{{ state_attr(person, 'latitude') }}"
      lon: "{{ state_attr(person, 'longitude') }}"
      acc: "{{ state_attr(person, 'gps_accuracy') or default_accuracy }}"

  - service: device_tracker.see
    data:
      dev_id: "{{ target.split('.')[-1] }}"
      gps:
        - "{{ lat }}"
        - "{{ lon }}"
      gps_accuracy: "{{ acc }}"
      source_type: gps
