blueprint:
  name: Light Link
  description: Link a light and a switch entity using the savedState Script
  domain: automation
  input:
    light_entity:
      name: Light
      selector:
        entity:
          filter:
            domain: light
    switch_entity:
      name: Switch
      selector:
        entity:
          filter:
            domain: switch
    conditions:
      name: Conditions
      selector:
        condition:
      default: []
    delay:
      name: Fade time
      selector:
        number:
          min: 0
          max: 20
          step: 0.5
          unit_of_measurement: "s"
      default: 2
mode: queued
max_exceeded: silent

variables:
  light_entity: !input light_entity
  switch_entity: !input switch_entity

triggers:
  - trigger: state
    entity_id: !input light_entity
    to: null
    id: light
  - trigger: state
    entity_id: !input switch_entity
    to: null
    id: switch

conditions:
  - alias: "States need to be different"
    condition: template
    value_template: "{{ states(light_entity) != states(switch_entity) }}"
  - condition: !input conditions

actions:
  - alias: "Distinguish Target and Trigger"
    choose:
    - conditions:
        - condition: trigger
          id: light
      sequence:
        - alias: "Toggle switch"
          service: switch.toggle
          target:
            entity_id: !input switch_entity
    - conditions:
        - condition: trigger
          id: switch
      sequence:
        - action: light.toggle
          metadata: {}
          data:
            transition: !input delay
          target:
            entity_id: !input light_entity